/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.demo

import kotlin.test.Test
import kotlin.test.assertFalse

class VersionTest {
    @Test
    fun gradleDemoVersion() {
        println(gradleDemoVersion)
        assertFalse(gradleDemoVersion == "Unknown")
    }
}
